#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
sh /$HOME/.config/scripts/autostart.sh &

bspc monitor -d I II III IV V

bspc config border_width 0
bspc config window_gap 10

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

bspc rule -a LibreWolf desktop='^1' follow=on
bspc rule -a Emacs desktop='^2' state=tiled follow=on
bspc rule -a rss desktop='^3' follow=on
bspc rule -a Binance desktop='^3' follow=on
bspc rule -a Caprine desktop='^4' follow=on
bspc rule -a floating state=floating

# removes the pointer cross mark
xsetroot -cursor_name left_ptr &
